### ISSUE TITLE
Which team corresponds to which code?

### ISSUE THREAD

**Issue by styler00dollar** [ofsoundof/NTIRE2022_ESR#2]
The chart provides an overview on how teams do compare and the repository lists architecture files. How can I tell which architecture file corresponds to which team? ByteESR for example, which python file would it be? It would be nice to also list architecture names in that table. Thanks.

**Comment by styler00dollar** [comment]
It turns out that i did not see [test_demo.py](https://github.com/ofsoundof/NTIRE2022_ESR/blob/main/test_demo.py) where teams are written in a comment. Closing issue.

**Comment by nanmehta** [comment]
is it possible, if we wish to check our code's accuracy on validation dataset

**Comment by ofsoundof** [comment]
> is it possible, if we wish to check our code's accuracy on validation dataset

Of course you can. Just download the DIV2K validation set and follow the [ReadMe](https://github.com/ofsoundof/NTIRE2022_ESR/blob/main/README.md) about how to use the repository.
